galaxy_info:
  author: Dominik Holler
  description: Role to install and configure the oVirt provider OVN driver on oVirt hypervisor.
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: 2.3

  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - 25

  galaxy_tags: [ovirt, rhv, rhev, virtualization, ovn]

dependencies: []
